import type { Notification } from './types';

export const seedNotifications: Notification[] = [
  {
    id: 'NOTIF-001',
    type: 'success',
    category: 'billing',
    icon: 'CheckCircle',
    title: 'Payment Completed',
    description: 'Payment of ₦15,000 received from patient Musa Ibrahim',
    message: 'Invoice GH-RC-0124 has been successfully paid. Amount: ₦15,000. Patient: Musa Ibrahim (GH-PT-00012). Payment method: Cash.',
    module: 'Billing',
    timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString(), // 30 minutes ago
    unread: true,
    actionLink: '/emr/dashboard/finance',
    actionLabel: 'View Invoice',
  },
  {
    id: 'NOTIF-002',
    type: 'info',
    category: 'clinical',
    icon: 'Calendar',
    title: 'Appointment Scheduled',
    description: 'New appointment scheduled for Aisha Bello with Dr. Usman',
    message: 'Appointment scheduled for tomorrow at 10:00 AM. Patient: Aisha Bello. Doctor: Dr. Usman Abdullahi. Department: Cardiology.',
    module: 'Appointments',
    timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(), // 1 hour ago
    unread: true,
    actionLink: '/emr/dashboard/appointments',
    actionLabel: 'View Appointment',
  },
  {
    id: 'NOTIF-003',
    type: 'success',
    category: 'clinical',
    icon: 'FlaskConical',
    title: 'Lab Result Ready',
    description: 'Laboratory test results available for Fatima Yusuf',
    message: 'Full Blood Count test results for patient Fatima Yusuf are now ready for review. Test ID: LAB-2025-0089.',
    module: 'Laboratory',
    timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(), // 1.5 hours ago
    unread: false,
    actionLink: '/emr/dashboard/laboratory',
    actionLabel: 'View Results',
  },
  {
    id: 'NOTIF-004',
    type: 'info',
    category: 'admin',
    icon: 'UserPlus',
    title: 'New Patient Registered',
    description: 'Patient Ibrahim Sani (GH-PT-00045) has been registered',
    message: 'A new patient has been added to the system. Name: Ibrahim Sani. File Number: GH-PT-00045. Type: Outpatient.',
    module: 'Patients',
    timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(), // 2 hours ago
    unread: false,
    actionLink: '/emr/dashboard/patients',
    actionLabel: 'View Patient',
  },
  {
    id: 'NOTIF-005',
    type: 'warning',
    category: 'clinical',
    icon: 'Bed',
    title: 'Bed Capacity Alert',
    description: 'General Ward is at 85% capacity',
    message: 'Warning: General Ward bed capacity has reached 85%. Total beds: 20. Occupied: 17. Available: 3. Please consider preparing overflow arrangements.',
    module: 'Beds',
    timestamp: new Date(Date.now() - 1000 * 60 * 180).toISOString(), // 3 hours ago
    unread: true,
    actionLink: '/emr/dashboard/rooms',
    actionLabel: 'View Bed Status',
  },
  {
    id: 'NOTIF-006',
    type: 'critical',
    category: 'admin',
    icon: 'AlertTriangle',
    title: 'Security Alert',
    description: 'Multiple failed login attempts detected',
    message: 'SECURITY ALERT: 5 failed login attempts detected for user account "receptionist@godiya.com" from IP 192.168.1.105. Account has been temporarily locked for security.',
    module: 'Security',
    timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(), // 4 hours ago
    unread: true,
    actionLink: '/emr/dashboard/administration',
    actionLabel: 'View Security Logs',
  },
  {
    id: 'NOTIF-007',
    type: 'success',
    category: 'admin',
    icon: 'UserCheck',
    title: 'Staff Login',
    description: 'Dr. Fatima Hassan logged into the system',
    message: 'User login successful. Name: Dr. Fatima Hassan. Role: Doctor. Department: Medical. Login time: ' + new Date(Date.now() - 1000 * 60 * 300).toLocaleString(),
    module: 'System',
    timestamp: new Date(Date.now() - 1000 * 60 * 300).toISOString(), // 5 hours ago
    unread: false,
  },
  {
    id: 'NOTIF-008',
    type: 'info',
    category: 'clinical',
    icon: 'Pill',
    title: 'Pharmacy Dispensation',
    description: 'Medication dispensed for patient Halima Mohammed',
    message: 'Prescription filled and medication dispensed. Patient: Halima Mohammed. Medications: Amoxicillin 500mg, Paracetamol 500mg. Pharmacist: John Okafor.',
    module: 'Pharmacy',
    timestamp: new Date(Date.now() - 1000 * 60 * 360).toISOString(), // 6 hours ago
    unread: false,
    actionLink: '/emr/dashboard/pharmacy',
    actionLabel: 'View Pharmacy',
  },
  {
    id: 'NOTIF-009',
    type: 'success',
    category: 'admin',
    icon: 'Database',
    title: 'System Backup Completed',
    description: 'Automated system backup completed successfully',
    message: 'Daily automated backup completed successfully. Backup size: 45.2 MB. Backup file: godiya-hospital-backup-2025-02-04.zip. All patient data, billing records, and system settings have been securely backed up.',
    module: 'System',
    timestamp: new Date(Date.now() - 1000 * 60 * 420).toISOString(), // 7 hours ago
    unread: false,
  },
  {
    id: 'NOTIF-010',
    type: 'warning',
    category: 'admin',
    icon: 'Clock',
    title: 'Staff Attendance Alert',
    description: '3 staff members marked as late today',
    message: 'Attendance Alert: 3 staff members checked in after 8:30 AM today. Please review attendance records in Staff Attendance Analytics.',
    module: 'Staff',
    timestamp: new Date(Date.now() - 1000 * 60 * 480).toISOString(), // 8 hours ago
    unread: false,
    actionLink: '/emr/dashboard/cms',
    actionLabel: 'View Attendance',
  },
  {
    id: 'NOTIF-011',
    type: 'info',
    category: 'admin',
    icon: 'Building',
    title: 'New Department Created',
    description: 'Physiotherapy Department has been added to the system',
    message: 'New department added: Physiotherapy. Type: Clinical. Initial staff count: 0. Created by: Super Admin.',
    module: 'Departments',
    timestamp: new Date(Date.now() - 1000 * 60 * 540).toISOString(), // 9 hours ago
    unread: false,
    actionLink: '/emr/dashboard/departments',
    actionLabel: 'View Departments',
  },
  {
    id: 'NOTIF-012',
    type: 'critical',
    category: 'admin',
    icon: 'XCircle',
    title: 'User Account Suspended',
    description: 'User account for nurse@godiya.com has been suspended',
    message: 'ADMIN ACTION: User account "nurse@godiya.com" (Amina Suleiman) has been suspended due to policy violations. All access privileges have been revoked immediately.',
    module: 'Security',
    timestamp: new Date(Date.now() - 1000 * 60 * 600).toISOString(), // 10 hours ago
    unread: false,
  },
  // Additional Clinical Notifications
  {
    id: 'NOTIF-013',
    type: 'warning',
    category: 'clinical',
    icon: 'Stethoscope',
    title: 'Patient Vital Signs Alert',
    description: 'Abnormal vital signs detected for patient Aminu Kano',
    message: 'ALERT: Patient Aminu Kano (GH-PT-00089) has abnormal vital signs. BP: 160/100, Pulse: 110 bpm, Temperature: 38.5°C. Immediate doctor consultation recommended.',
    module: 'Patients',
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(), // 45 minutes ago
    unread: true,
    actionLink: '/emr/dashboard/patients',
    actionLabel: 'View Patient',
  },
  {
    id: 'NOTIF-014',
    type: 'info',
    category: 'clinical',
    icon: 'Syringe',
    title: 'Vaccination Due',
    description: 'Child immunization due for Baby Zainab',
    message: 'Immunization reminder: Baby Zainab Mohammed is due for BCG vaccination today. Please schedule appointment with vaccination clinic.',
    module: 'Appointments',
    timestamp: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
    unread: true,
    actionLink: '/emr/dashboard/appointments',
    actionLabel: 'Schedule Vaccination',
  },
  {
    id: 'NOTIF-015',
    type: 'success',
    category: 'clinical',
    icon: 'Activity',
    title: 'Surgery Completed',
    description: 'Appendectomy surgery completed successfully',
    message: 'Surgery Update: Appendectomy procedure for patient Mohammed Bello completed successfully. Duration: 45 minutes. Patient transferred to recovery room. Surgeon: Dr. Ibrahim Sanusi.',
    module: 'Patients',
    timestamp: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
    unread: false,
  },
  {
    id: 'NOTIF-016',
    type: 'critical',
    category: 'clinical',
    icon: 'AlertTriangle',
    title: 'Emergency Patient Admitted',
    description: 'Critical patient admitted to Emergency Ward',
    message: 'EMERGENCY: Critical patient admitted with severe trauma. Patient: Unknown Male, Age ~35. Condition: Multiple injuries from RTA. Attending: Dr. Aisha Musa. Requires immediate blood transfusion (O+ blood type).',
    module: 'Patients',
    timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    unread: true,
  },
  // Additional Billing Notifications
  {
    id: 'NOTIF-017',
    type: 'warning',
    category: 'billing',
    icon: 'DollarSign',
    title: 'Outstanding Payment Alert',
    description: 'Patient Suleiman Yusuf has overdue payment',
    message: 'Payment Alert: Patient Suleiman Yusuf (GH-PT-00234) has an outstanding balance of ₦45,000 for over 30 days. Invoice: GH-RC-0089. Please follow up for payment collection.',
    module: 'Billing',
    timestamp: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    unread: true,
    actionLink: '/emr/dashboard/finance',
    actionLabel: 'View Invoice',
  },
  {
    id: 'NOTIF-018',
    type: 'success',
    category: 'billing',
    icon: 'CheckCircle',
    title: 'NHIS Claim Approved',
    description: 'Insurance claim for Abubakar Hassan approved',
    message: 'Insurance Update: NHIS claim for patient Abubakar Hassan (Claim ID: NHIS-2025-145) has been approved. Amount: ₦28,500. Payment expected within 14 business days.',
    module: 'Billing',
    timestamp: new Date(Date.now() - 1000 * 60 * 250).toISOString(),
    unread: false,
  },
  {
    id: 'NOTIF-019',
    type: 'info',
    category: 'billing',
    icon: 'Receipt',
    title: 'Daily Revenue Report',
    description: 'Daily revenue summary generated',
    message: 'Revenue Report: Total revenue collected today: ₦485,000. Breakdown - Consultations: ₦125,000, Pharmacy: ₦180,000, Laboratory: ₦95,000, Admissions: ₦85,000.',
    module: 'Billing',
    timestamp: new Date(Date.now() - 1000 * 60 * 320).toISOString(),
    unread: false,
  },
  {
    id: 'NOTIF-020',
    type: 'critical',
    category: 'billing',
    icon: 'AlertCircle',
    title: 'Payment Declined',
    description: 'Card payment declined for patient Hauwa Abdullahi',
    message: 'Payment Failed: Card payment of ₦12,500 for patient Hauwa Abdullahi was declined. Reason: Insufficient funds. Please request alternative payment method.',
    module: 'Billing',
    timestamp: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    unread: true,
  },
  // Additional Admin Notifications
  {
    id: 'NOTIF-021',
    type: 'info',
    category: 'admin',
    icon: 'Users',
    title: 'New Staff Onboarded',
    description: 'New nurse joined the Medical Department',
    message: 'Staff Update: Maryam Suleiman has been onboarded as a Nurse in the Medical Department. Employee ID: GH-ST-0156. Start Date: Today.',
    module: 'Staff',
    timestamp: new Date(Date.now() - 1000 * 60 * 280).toISOString(),
    unread: false,
    actionLink: '/emr/dashboard/cms',
    actionLabel: 'View Staff',
  },
  {
    id: 'NOTIF-022',
    type: 'warning',
    category: 'admin',
    icon: 'Shield',
    title: 'System Maintenance Scheduled',
    description: 'Scheduled maintenance on February 6, 2025',
    message: 'Maintenance Notice: System maintenance scheduled for February 6, 2025 from 2:00 AM to 4:00 AM. The EMR system will be temporarily unavailable. Please plan accordingly.',
    module: 'System',
    timestamp: new Date(Date.now() - 1000 * 60 * 350).toISOString(),
    unread: false,
  },
  {
    id: 'NOTIF-023',
    type: 'success',
    category: 'admin',
    icon: 'CheckCircle2',
    title: 'Role Permissions Updated',
    description: 'Receptionist role permissions modified',
    message: 'Permission Change: Receptionist role permissions have been updated. New permissions added: Export Reports, View Finance Summary. Updated by: Super Admin.',
    module: 'Security',
    timestamp: new Date(Date.now() - 1000 * 60 * 400).toISOString(),
    unread: false,
  },
  {
    id: 'NOTIF-024',
    type: 'info',
    category: 'admin',
    icon: 'FileText',
    title: 'Monthly Report Generated',
    description: 'January 2025 hospital statistics ready',
    message: 'Monthly Report: January 2025 statistics compiled. Total Patients: 1,245, Revenue: ₦8.5M, Appointments: 3,420, Lab Tests: 2,156. Report available in Reports module.',
    module: 'System',
    timestamp: new Date(Date.now() - 1000 * 60 * 500).toISOString(),
    unread: false,
    actionLink: '/emr/dashboard/reports',
    actionLabel: 'View Report',
  },
];