import { Patient, Appointment, Invoice, Doctor, Staff, Department, BedCategory } from './types';

// Calculate age from date of birth
function calculateAge(dob: string): number {
  const birthDate = new Date(dob);
  const today = new Date();
  let age = today.getFullYear() - birthDate.getFullYear();
  const monthDiff = today.getMonth() - birthDate.getMonth();
  if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {
    age--;
  }
  return age;
}

// Seed Departments
export const seedDepartments: Department[] = [
  {
    id: 'GH-DP-001',
    name: 'Pharmacy',
    type: 'Clinical',
    description: 'Drug dispensing & prescription management',
    staffCount: 3,
    status: 'Active',
    icon: 'Pill',
    dateCreated: '2025-01-01T08:00:00',
    lastUpdated: '2025-02-02T10:30:00',
  },
  {
    id: 'GH-DP-002',
    name: 'Laboratory',
    type: 'Clinical',
    description: 'Diagnostic testing & results analysis',
    staffCount: 4,
    status: 'Active',
    icon: 'FlaskConical',
    dateCreated: '2025-01-01T08:00:00',
    lastUpdated: '2025-02-02T10:30:00',
  },
  {
    id: 'GH-DP-003',
    name: 'Records',
    type: 'Support',
    description: 'Patient file and document management',
    staffCount: 2,
    status: 'Active',
    icon: 'FolderOpen',
    dateCreated: '2025-01-01T08:00:00',
    lastUpdated: '2025-02-02T10:30:00',
  },
  {
    id: 'GH-DP-004',
    name: 'Nurses',
    type: 'Clinical',
    description: 'Patient care and vitals monitoring',
    staffCount: 8,
    status: 'Active',
    icon: 'Stethoscope',
    dateCreated: '2025-01-01T08:00:00',
    lastUpdated: '2025-02-02T10:30:00',
  },
  {
    id: 'GH-DP-005',
    name: 'Doctors',
    type: 'Clinical',
    description: 'Consultation & treatment',
    staffCount: 6,
    status: 'Active',
    icon: 'UserCog',
    dateCreated: '2025-01-01T08:00:00',
    lastUpdated: '2025-02-02T10:30:00',
  },
  {
    id: 'GH-DP-006',
    name: 'Radiology',
    type: 'Support',
    description: 'Imaging and scan services',
    staffCount: 2,
    status: 'Active',
    icon: 'ScanLine',
    dateCreated: '2025-01-01T08:00:00',
    lastUpdated: '2025-02-02T10:30:00',
  },
  {
    id: 'GH-DP-007',
    name: 'Physiotherapy',
    type: 'Support',
    description: 'Physical therapy & rehabilitation',
    staffCount: 1,
    status: 'Active',
    icon: 'Activity',
    dateCreated: '2025-01-01T08:00:00',
    lastUpdated: '2025-02-02T10:30:00',
  },
];

// Seed Doctors
export const seedDoctors: Doctor[] = [
  { id: 'DOC-001', name: 'Dr. Musa Abdullahi', department: 'General Medicine', specialization: 'General Practitioner' },
  { id: 'DOC-002', name: 'Dr. Zainab Ibrahim', department: 'Pediatrics', specialization: 'Pediatrician' },
  { id: 'DOC-003', name: 'Dr. Yakubu Bello', department: 'Surgery', specialization: 'General Surgeon' },
  { id: 'DOC-004', name: 'Dr. Hauwa Sani', department: 'Obstetrics & Gynecology', specialization: 'Obstetrician' },
  { id: 'DOC-005', name: 'Dr. Abdulrahman Lawal', department: 'Radiology', specialization: 'Radiologist' },
  { id: 'DOC-006', name: 'Dr. Maryam Yusuf', department: 'Family Medicine', specialization: 'Family Physician' },
];

// Seed Patients
export const seedPatients: Patient[] = [
  // Family File: Bello Family
  {
    id: 'GH-PT-F001',
    firstName: 'Bello',
    lastName: 'Family',
    fullName: 'Bello Family',
    gender: 'Male', // Head of family
    dateOfBirth: '1975-05-10',
    age: calculateAge('1975-05-10'),
    phoneNumber: '08012345600',
    address: 'No. 12 Kano Road, Birnin Kebbi',
    patientType: 'Outpatient',
    status: 'Active',
    emergencyContactName: 'Extended Family',
    emergencyContactPhone: '08098765400',
    notes: 'Family file - 3 members',
    dateRegistered: '2025-01-10T08:00:00',
    nextOfKin: 'Extended Family',
    fileType: 'Family',
    isDead: false,
  },
  {
    id: 'GH-PT-00001',
    firstName: 'Aisha',
    lastName: 'Bello',
    fullName: 'Aisha Bello',
    gender: 'Female',
    dateOfBirth: '1985-03-15',
    age: calculateAge('1985-03-15'),
    phoneNumber: '08012345601',
    address: 'No. 12 Kano Road, Birnin Kebbi',
    patientType: 'Outpatient',
    status: 'Active',
    emergencyContactName: 'Musa Bello',
    emergencyContactPhone: '08098765401',
    notes: 'Regular checkup patient - Wife - NHIS Enrolled',
    dateRegistered: '2025-01-15T08:30:00',
    nextOfKin: 'Musa Bello (Husband)',
    fileType: 'Individual',
    parentFileId: 'GH-PT-F001',
    isDead: false,
    // NHIS enrollment
    isNHIS: true,
    nhisNumber: 'NHIS-KB-2025-001234',
    nhisProvider: 'Hygeia HMO',
  },
  {
    id: 'GH-PT-00001A',
    firstName: 'Musa',
    lastName: 'Bello',
    fullName: 'Musa Bello',
    gender: 'Male',
    dateOfBirth: '1980-08-20',
    age: calculateAge('1980-08-20'),
    phoneNumber: '08098765401',
    address: 'No. 12 Kano Road, Birnin Kebbi',
    patientType: 'Outpatient',
    status: 'Active',
    emergencyContactName: 'Aisha Bello',
    emergencyContactPhone: '08012345601',
    notes: 'Husband - Regular checkup',
    dateRegistered: '2025-01-15T08:30:00',
    nextOfKin: 'Aisha Bello (Wife)',
    fileType: 'Individual',
    parentFileId: 'GH-PT-F001',
    isDead: false,
  },
  {
    id: 'GH-PT-00001B',
    firstName: 'Amina',
    lastName: 'Bello',
    fullName: 'Amina Bello',
    gender: 'Female',
    dateOfBirth: '2015-02-12',
    age: calculateAge('2015-02-12'),
    phoneNumber: '08012345601',
    address: 'No. 12 Kano Road, Birnin Kebbi',
    patientType: 'Outpatient',
    status: 'Active',
    emergencyContactName: 'Aisha Bello',
    emergencyContactPhone: '08012345601',
    notes: 'Daughter - Immunization schedule',
    dateRegistered: '2025-01-15T08:30:00',
    nextOfKin: 'Aisha Bello (Mother)',
    fileType: 'Individual',
    parentFileId: 'GH-PT-F001',
    isDead: false,
  },
  // Family File: Yusuf Family
  {
    id: 'GH-PT-F002',
    firstName: 'Yusuf',
    lastName: 'Family',
    fullName: 'Yusuf Family',
    gender: 'Male',
    dateOfBirth: '1978-07-22',
    age: calculateAge('1978-07-22'),
    phoneNumber: '08023456702',
    address: 'No. 45 Sokoto Road, Birnin Kebbi',
    patientType: 'Inpatient',
    status: 'Admitted',
    emergencyContactName: 'Extended Family',
    emergencyContactPhone: '08087654302',
    notes: 'Family file - 2 members',
    dateRegistered: '2025-01-12T09:00:00',
    nextOfKin: 'Extended Family',
    fileType: 'Family',
    isDead: false,
  },
  {
    id: 'GH-PT-00002',
    firstName: 'Ibrahim',
    lastName: 'Yusuf',
    fullName: 'Ibrahim Yusuf',
    gender: 'Male',
    dateOfBirth: '1978-07-22',
    age: calculateAge('1978-07-22'),
    phoneNumber: '08023456702',
    address: 'No. 45 Sokoto Road, Birnin Kebbi',
    patientType: 'Inpatient',
    status: 'Admitted',
    emergencyContactName: 'Fatima Yusuf',
    emergencyContactPhone: '08087654302',
    notes: 'Admitted for malaria treatment - Husband',
    dateRegistered: '2025-01-20T10:15:00',
    nextOfKin: 'Fatima Yusuf (Wife)',
    fileType: 'Individual',
    parentFileId: 'GH-PT-F002',
    isDead: false,
  },
  {
    id: 'GH-PT-00002A',
    firstName: 'Fatima',
    lastName: 'Yusuf',
    fullName: 'Fatima Yusuf',
    gender: 'Female',
    dateOfBirth: '1982-11-14',
    age: calculateAge('1982-11-14'),
    phoneNumber: '08087654302',
    address: 'No. 45 Sokoto Road, Birnin Kebbi',
    patientType: 'Outpatient',
    status: 'Active',
    emergencyContactName: 'Ibrahim Yusuf',
    emergencyContactPhone: '08023456702',
    notes: 'Wife - Regular checkup',
    dateRegistered: '2025-01-20T10:15:00',
    nextOfKin: 'Ibrahim Yusuf (Husband)',
    fileType: 'Individual',
    parentFileId: 'GH-PT-F002',
    isDead: false,
  },
  {
    id: 'GH-PT-00003',
    firstName: 'Fatima',
    lastName: 'Usman',
    fullName: 'Fatima Usman',
    gender: 'Female',
    dateOfBirth: '1992-11-08',
    age: calculateAge('1992-11-08'),
    phoneNumber: '08034567803',
    address: 'No. 23 Gesse Road, Birnin Kebbi',
    patientType: 'Outpatient',
    status: 'Active',
    emergencyContactName: 'Usman Ali',
    emergencyContactPhone: '08076543203',
    notes: 'ANC patient',
    dateRegistered: '2025-01-22T14:20:00',
    nextOfKin: 'Usman Ali (Husband)',
    fileType: 'Individual',
    isDead: false,
  },
  {
    id: 'GH-PT-00004',
    firstName: 'Musa',
    lastName: 'Garba',
    fullName: 'Musa Garba',
    gender: 'Male',
    dateOfBirth: '2010-05-30',
    age: calculateAge('2010-05-30'),
    phoneNumber: '08045678904',
    address: 'No. 67 Zuru Road, Birnin Kebbi',
    patientType: 'ER',
    status: 'Active',
    emergencyContactName: 'Halima Garba',
    emergencyContactPhone: '08065432104',
    notes: 'Emergency admission - accident',
    dateRegistered: '2025-01-25T16:45:00',
    nextOfKin: 'Halima Garba (Mother)',
    fileType: 'Individual',
    isDead: false,
  },
  {
    id: 'GH-PT-00005',
    firstName: 'Zainab',
    lastName: 'Mohammed',
    fullName: 'Zainab Mohammed',
    gender: 'Female',
    dateOfBirth: '1965-09-12',
    age: calculateAge('1965-09-12'),
    phoneNumber: '08056789005',
    address: 'No. 89 Argungu Road, Birnin Kebbi',
    patientType: 'ICU',
    status: 'Admitted',
    emergencyContactName: 'Ahmed Mohammed',
    emergencyContactPhone: '08054321005',
    notes: 'ICU - post surgery monitoring',
    dateRegistered: '2025-01-23T09:00:00',
    nextOfKin: 'Ahmed Mohammed (Son)',
    fileType: 'Individual',
    isDead: false,
  },
  {
    id: 'GH-PT-00006',
    firstName: 'Yusuf',
    lastName: 'Sani',
    fullName: 'Yusuf Sani',
    gender: 'Male',
    dateOfBirth: '1958-02-18',
    age: calculateAge('1958-02-18'),
    phoneNumber: '08067890106',
    address: 'No. 34 Kalgo Road, Birnin Kebbi',
    patientType: 'COPD',
    status: 'Active',
    emergencyContactName: 'Halima Sani',
    emergencyContactPhone: '08043210906',
    notes: 'COPD patient - regular monitoring',
    dateRegistered: '2025-01-18T11:30:00',
    nextOfKin: 'Halima Sani (Wife)',
    fileType: 'Individual',
    isDead: false,
  },
  {
    id: 'GH-PT-00007',
    firstName: 'Hauwa',
    lastName: 'Abdullahi',
    fullName: 'Hauwa Abdullahi',
    gender: 'Female',
    dateOfBirth: '1995-06-25',
    age: calculateAge('1995-06-25'),
    phoneNumber: '08078901207',
    address: 'No. 56 Maiyama Road, Birnin Kebbi',
    patientType: 'Outpatient',
    status: 'Pending Payment',
    emergencyContactName: 'Ibrahim Abdullahi',
    emergencyContactPhone: '08032109807',
    notes: 'Pending payment for lab tests',
    dateRegistered: '2025-01-24T13:45:00',
    nextOfKin: 'Ibrahim Abdullahi (Brother)',
    fileType: 'Individual',
    isDead: false,
  },
  {
    id: 'GH-PT-00008',
    firstName: 'Aliyu',
    lastName: 'Ibrahim',
    fullName: 'Aliyu Ibrahim',
    gender: 'Male',
    dateOfBirth: '1988-12-03',
    age: calculateAge('1988-12-03'),
    phoneNumber: '08089012308',
    address: 'No. 78 Jega Road, Birnin Kebbi',
    patientType: 'Inpatient',
    status: 'Admitted',
    emergencyContactName: 'Amina Ibrahim',
    emergencyContactPhone: '08021098708',
    notes: 'Admitted for observation',
    dateRegistered: '2025-01-21T15:20:00',
    nextOfKin: 'Amina Ibrahim (Wife)',
    fileType: 'Individual',
    isDead: false,
  },
  {
    id: 'GH-PT-00009',
    firstName: 'Khadija',
    lastName: 'Lawal',
    fullName: 'Khadija Lawal',
    gender: 'Female',
    dateOfBirth: '2015-08-14',
    age: calculateAge('2015-08-14'),
    phoneNumber: '08090123409',
    address: 'No. 90 Bunza Road, Birnin Kebbi',
    patientType: 'Outpatient',
    status: 'Active',
    emergencyContactName: 'Rukayya Lawal',
    emergencyContactPhone: '08010987609',
    notes: 'Immunization schedule',
    dateRegistered: '2025-01-19T10:00:00',
    nextOfKin: 'Rukayya Lawal (Mother)',
    fileType: 'Individual',
    isDead: false,
  },
  {
    id: 'GH-PT-00010',
    firstName: 'Umar',
    lastName: 'Hassan',
    fullName: 'Umar Hassan',
    gender: 'Male',
    dateOfBirth: '1975-04-20',
    age: calculateAge('1975-04-20'),
    phoneNumber: '08001234510',
    address: 'No. 12 Yauri Road, Birnin Kebbi',
    patientType: 'ER',
    status: 'Active',
    emergencyContactName: 'Safiya Hassan',
    emergencyContactPhone: '08009876510',
    notes: 'ER - chest pain',
    dateRegistered: '2025-01-26T07:30:00',
    nextOfKin: 'Safiya Hassan (Wife)',
    fileType: 'Individual',
    isDead: false,
  },
  {
    id: 'GH-PT-00011',
    firstName: 'Ramatu',
    lastName: 'Musa',
    fullName: 'Ramatu Musa',
    gender: 'Female',
    dateOfBirth: '1990-10-05',
    age: calculateAge('1990-10-05'),
    phoneNumber: '08012345611',
    address: 'No. 34 Gwandu Road, Birnin Kebbi',
    patientType: 'Outpatient',
    status: 'Discharged',
    emergencyContactName: 'Sani Musa',
    emergencyContactPhone: '08098765411',
    notes: 'Treatment completed',
    dateRegistered: '2025-01-10T09:15:00',
    nextOfKin: 'Sani Musa (Husband)',
    fileType: 'Individual',
    isDead: false,
  },
  {
    id: 'GH-PT-00012',
    firstName: 'Suleiman',
    lastName: 'Ahmed',
    fullName: 'Suleiman Ahmed',
    gender: 'Male',
    dateOfBirth: '2005-01-28',
    age: calculateAge('2005-01-28'),
    phoneNumber: '08023456712',
    address: 'No. 56 Ribah Road, Birnin Kebbi',
    patientType: 'Outpatient',
    status: 'Active',
    emergencyContactName: 'Hadiza Ahmed',
    emergencyContactPhone: '08087654312',
    notes: 'Follow-up appointment scheduled',
    dateRegistered: '2025-01-23T11:00:00',
    nextOfKin: 'Hadiza Ahmed (Mother)',
    fileType: 'Individual',
    isDead: false,
  },
  {
    id: 'GH-PT-00013',
    firstName: 'Amina',
    lastName: 'Balarabe',
    fullName: 'Amina Balarabe',
    gender: 'Female',
    dateOfBirth: '1982-07-17',
    age: calculateAge('1982-07-17'),
    phoneNumber: '08034567813',
    address: 'No. 78 Shanga Road, Birnin Kebbi',
    patientType: 'Inpatient',
    status: 'Admitted',
    emergencyContactName: 'Balarabe Usman',
    emergencyContactPhone: '08076543213',
    notes: 'Maternity ward',
    dateRegistered: '2025-01-24T16:30:00',
    nextOfKin: 'Balarabe Usman (Husband)',
    fileType: 'Individual',
    isDead: false,
  },
  {
    id: 'GH-PT-00014',
    firstName: 'Faruk',
    lastName: 'Ibrahim',
    fullName: 'Faruk Ibrahim',
    gender: 'Male',
    dateOfBirth: '1968-03-09',
    age: calculateAge('1968-03-09'),
    phoneNumber: '08045678914',
    address: 'No. 90 Danko Road, Birnin Kebbi',
    patientType: 'COPD',
    status: 'Active',
    emergencyContactName: 'Aisha Ibrahim',
    emergencyContactPhone: '08065432114',
    notes: 'COPD management plan',
    dateRegistered: '2025-01-17T14:45:00',
    nextOfKin: 'Aisha Ibrahim (Wife)',
    fileType: 'Individual',
    isDead: false,
  },
  {
    id: 'GH-PT-00015',
    firstName: 'Salamatu',
    lastName: 'Yakubu',
    fullName: 'Salamatu Yakubu',
    gender: 'Female',
    dateOfBirth: '2018-11-22',
    age: calculateAge('2018-11-22'),
    phoneNumber: '08056789015',
    address: 'No. 12 Bagudo Road, Birnin Kebbi',
    patientType: 'Outpatient',
    status: 'Active',
    emergencyContactName: 'Zainab Yakubu',
    emergencyContactPhone: '08054321015',
    notes: 'Pediatric checkup',
    dateRegistered: '2025-01-25T10:30:00',
    nextOfKin: 'Zainab Yakubu (Mother)',
    fileType: 'Individual',
    isDead: false,
  },
  // VIP Patient with Extensive Medical History - Long-term patient
  {
    id: 'GH-PT-00016',
    firstName: 'Alhaji Usman',
    lastName: 'Gwandu',
    fullName: 'Alhaji Usman Gwandu',
    gender: 'Male',
    dateOfBirth: '1955-08-15',
    age: calculateAge('1955-08-15'),
    phoneNumber: '08091234567',
    address: 'No. 3 GRA, Government Reserved Area, Birnin Kebbi',
    patientType: 'Outpatient',
    status: 'Active',
    emergencyContactName: 'Dr. Aminu Gwandu',
    emergencyContactPhone: '08091234568',
    notes: 'VIP Patient - Long-term care (since 2010). Chronic conditions: Type 2 Diabetes (2010), Hypertension (2012), Chronic Kidney Disease Stage 3 (2018). Regular monthly checkups. Previous admissions: Pneumonia (Jan 2020), Cardiac event (Aug 2021), Kidney complications (Mar 2023). Current medications: Metformin 1000mg BD, Amlodipine 10mg OD, Insulin Glargine 20 units at bedtime, Aspirin 75mg OD. Allergies: Penicillin (severe rash). Last visit: Jan 28, 2025 - Blood sugar monitoring and BP check. Next scheduled: Feb 15, 2025 - Nephrology consultation. Family history: Father died of kidney failure, Mother had diabetes. Lives with son (Dr. Aminu). NHIS enrolled. Requires wheelchair assistance. Diet: Low sodium, diabetic diet.',
    dateRegistered: '2010-03-15T09:00:00',
    nextOfKin: 'Dr. Aminu Gwandu (Son)',
    fileType: 'Individual',
    isDead: false,
    isNHIS: true,
    nhisNumber: 'NHIS-KB-2010-000145',
    nhisProvider: 'Reliance HMO',
  },
  // Additional Inpatient records
  {
    id: 'GH-PT-00017',
    firstName: 'Halima',
    lastName: 'Sani',
    fullName: 'Halima Sani',
    gender: 'Female',
    dateOfBirth: '1992-06-10',
    age: calculateAge('1992-06-10'),
    phoneNumber: '08087654321',
    address: 'No. 78 Argungu Road, Birnin Kebbi',
    patientType: 'Inpatient',
    status: 'Admitted',
    emergencyContactName: 'Abubakar Sani',
    emergencyContactPhone: '08087654320',
    notes: 'Admitted for cesarean section - Emergency C-section scheduled',
    dateRegistered: '2025-02-01T14:30:00',
    nextOfKin: 'Abubakar Sani (Husband)',
    fileType: 'Individual',
    isDead: false,
  },
  {
    id: 'GH-PT-00018',
    firstName: 'Yusuf',
    lastName: 'Mohammed',
    fullName: 'Yusuf Mohammed',
    gender: 'Male',
    dateOfBirth: '2005-12-20',
    age: calculateAge('2005-12-20'),
    phoneNumber: '08067891234',
    address: 'No. 15 Kalgo Road, Birnin Kebbi',
    patientType: 'Inpatient',
    status: 'Admitted',
    emergencyContactName: 'Hadiza Mohammed',
    emergencyContactPhone: '08067891233',
    notes: 'Admitted with severe malaria and dehydration - ICU monitoring',
    dateRegistered: '2025-01-30T18:45:00',
    nextOfKin: 'Hadiza Mohammed (Mother)',
    fileType: 'Individual',
    isDead: false,
  },
  {
    id: 'GH-PT-00019',
    firstName: 'Rahama',
    lastName: 'Umar',
    fullName: 'Rahama Umar',
    gender: 'Female',
    dateOfBirth: '1988-04-25',
    age: calculateAge('1988-04-25'),
    phoneNumber: '08076543210',
    address: 'No. 34 Yauri Road, Birnin Kebbi',
    patientType: 'Inpatient',
    status: 'Admitted',
    emergencyContactName: 'Umar Ibrahim',
    emergencyContactPhone: '08076543211',
    notes: 'Post-operative care - Appendectomy performed yesterday',
    dateRegistered: '2025-01-31T08:20:00',
    nextOfKin: 'Umar Ibrahim (Brother)',
    fileType: 'Individual',
    isDead: false,
  },
  // Additional Outpatient records
  {
    id: 'GH-PT-00020',
    firstName: 'Sadiq',
    lastName: 'Ahmad',
    fullName: 'Sadiq Ahmad',
    gender: 'Male',
    dateOfBirth: '1998-09-12',
    age: calculateAge('1998-09-12'),
    phoneNumber: '08098765432',
    address: 'No. 67 Zuru Road, Birnin Kebbi',
    patientType: 'Outpatient',
    status: 'Active',
    emergencyContactName: 'Fatima Ahmad',
    emergencyContactPhone: '08098765431',
    notes: 'Routine dental checkup scheduled',
    dateRegistered: '2025-01-28T11:00:00',
    nextOfKin: 'Fatima Ahmad (Sister)',
    fileType: 'Individual',
    isDead: false,
  },
  {
    id: 'GH-PT-00021',
    firstName: 'Zahra',
    lastName: 'Aliyu',
    fullName: 'Zahra Aliyu',
    gender: 'Female',
    dateOfBirth: '2010-03-30',
    age: calculateAge('2010-03-30'),
    phoneNumber: '08034567890',
    address: 'No. 89 Gwandu Road, Birnin Kebbi',
    patientType: 'Outpatient',
    status: 'Active',
    emergencyContactName: 'Maryam Aliyu',
    emergencyContactPhone: '08034567891',
    notes: 'Child immunization - Polio and Measles vaccine',
    dateRegistered: '2025-01-26T09:15:00',
    nextOfKin: 'Maryam Aliyu (Mother)',
    fileType: 'Individual',
    isDead: false,
  },
  {
    id: 'GH-PT-00022',
    firstName: 'Bashir',
    lastName: 'Dankani',
    fullName: 'Bashir Dankani',
    gender: 'Male',
    dateOfBirth: '1975-11-18',
    age: calculateAge('1975-11-18'),
    phoneNumber: '08087654309',
    address: 'No. 23 Jega Road, Birnin Kebbi',
    patientType: 'Outpatient',
    status: 'Active',
    emergencyContactName: 'Hajiya Hauwa Dankani',
    emergencyContactPhone: '08087654308',
    notes: 'Hypertension follow-up visit',
    dateRegistered: '2024-06-10T10:00:00',
    nextOfKin: 'Hajiya Hauwa Dankani (Wife)',
    fileType: 'Individual',
    isDead: false,
  },
  {
    id: 'GH-PT-00023',
    firstName: 'Maimuna',
    lastName: 'Bala',
    fullName: 'Maimuna Bala',
    gender: 'Female',
    dateOfBirth: '2000-07-05',
    age: calculateAge('2000-07-05'),
    phoneNumber: '08056781234',
    address: 'No. 41 Maiyama Road, Birnin Kebbi',
    patientType: 'Outpatient',
    status: 'Active',
    emergencyContactName: 'Bala Garba',
    emergencyContactPhone: '08056781235',
    notes: 'Pre-wedding health screening',
    dateRegistered: '2025-01-29T13:45:00',
    nextOfKin: 'Bala Garba (Father)',
    fileType: 'Individual',
    isDead: false,
  },
  {
    id: 'GH-PT-00024',
    firstName: 'Kabir',
    lastName: 'Hassan',
    fullName: 'Kabir Hassan',
    gender: 'Male',
    dateOfBirth: '1985-02-14',
    age: calculateAge('1985-02-14'),
    phoneNumber: '08091237845',
    address: 'No. 56 Sani Abacha Way, Birnin Kebbi',
    patientType: 'Inpatient',
    status: 'Admitted',
    emergencyContactName: 'Aisha Hassan',
    emergencyContactPhone: '08091237844',
    notes: 'Admitted for pneumonia treatment and observation',
    dateRegistered: '2025-01-29T20:30:00',
    nextOfKin: 'Aisha Hassan (Wife)',
    fileType: 'Individual',
    isDead: false,
  },
  {
    id: 'GH-PT-00025',
    firstName: 'Nafisa',
    lastName: 'Garba',
    fullName: 'Nafisa Garba',
    gender: 'Female',
    dateOfBirth: '2019-01-08',
    age: calculateAge('2019-01-08'),
    phoneNumber: '08076549012',
    address: 'No. 92 Dakingari Road, Birnin Kebbi',
    patientType: 'Outpatient',
    status: 'Active',
    emergencyContactName: 'Zainab Garba',
    emergencyContactPhone: '08076549013',
    notes: 'Pediatric consultation for fever and cough',
    dateRegistered: '2025-02-01T08:00:00',
    nextOfKin: 'Zainab Garba (Mother)',
    fileType: 'Individual',
    isDead: false,
  },
  {
    id: 'GH-PT-00026',
    firstName: 'Sanusi',
    lastName: 'Ibrahim',
    fullName: 'Sanusi Ibrahim',
    gender: 'Male',
    dateOfBirth: '1968-10-30',
    age: calculateAge('1968-10-30'),
    phoneNumber: '08087659876',
    address: 'No. 18 Magaji Street, Birnin Kebbi',
    patientType: 'Inpatient',
    status: 'Admitted',
    emergencyContactName: 'Amina Ibrahim',
    emergencyContactPhone: '08087659877',
    notes: 'Admitted for cardiac monitoring - Suspected angina',
    dateRegistered: '2025-01-31T22:15:00',
    nextOfKin: 'Amina Ibrahim (Wife)',
    fileType: 'Individual',
    isDead: false,
  },
  {
    id: 'GH-PT-00027',
    firstName: 'Jamila',
    lastName: 'Abubakar',
    fullName: 'Jamila Abubakar',
    gender: 'Female',
    dateOfBirth: '1995-05-20',
    age: calculateAge('1995-05-20'),
    phoneNumber: '08034562109',
    address: 'No. 27 Bunza Road, Birnin Kebbi',
    patientType: 'Outpatient',
    status: 'Active',
    emergencyContactName: 'Usman Abubakar',
    emergencyContactPhone: '08034562108',
    notes: 'Antenatal booking - First trimester',
    dateRegistered: '2025-01-27T14:20:00',
    nextOfKin: 'Usman Abubakar (Husband)',
    fileType: 'Individual',
    isDead: false,
    isNHIS: true,
    nhisNumber: 'NHIS-KB-2024-008765',
    nhisProvider: 'AXA Mansard HMO',
  },
];

// Seed Appointments
export const seedAppointments: Appointment[] = [
  {
    id: 'GH-AP-0001',
    patientId: 'GH-PT-00001',
    patientName: 'Aisha Bello',
    appointmentType: 'Consultation',
    department: 'General Medicine',
    doctorName: 'Dr. Musa Abdullahi',
    date: new Date().toISOString().split('T')[0],
    time: 'Morning',
    priority: 'Normal',
    status: 'Scheduled',
    notes: 'General checkup',
  },
  {
    id: 'GH-AP-0002',
    patientId: 'GH-PT-00003',
    patientName: 'Fatima Usman',
    appointmentType: 'ANC',
    department: 'Obstetrics & Gynecology',
    doctorName: 'Dr. Hauwa Sani',
    date: new Date().toISOString().split('T')[0],
    time: 'Afternoon',
    priority: 'Normal',
    status: 'In Progress',
    notes: 'Antenatal care visit',
  },
  {
    id: 'GH-AP-0003',
    patientId: 'GH-PT-00006',
    patientName: 'Yusuf Sani',
    appointmentType: 'Follow-up',
    department: 'General Medicine',
    doctorName: 'Dr. Musa Abdullahi',
    date: new Date().toISOString().split('T')[0],
    time: 'Morning',
    priority: 'High',
    status: 'Scheduled',
    notes: 'COPD follow-up',
  },
  {
    id: 'GH-AP-0004',
    patientId: 'GH-PT-00009',
    patientName: 'Khadija Lawal',
    appointmentType: 'Immunization',
    department: 'Pediatrics',
    doctorName: 'Dr. Zainab Ibrahim',
    date: new Date().toISOString().split('T')[0],
    time: 'Afternoon',
    priority: 'Normal',
    status: 'Scheduled',
    notes: 'Routine immunization',
  },
  {
    id: 'GH-AP-0005',
    patientId: 'GH-PT-00012',
    patientName: 'Suleiman Ahmed',
    appointmentType: 'Follow-up',
    department: 'Pediatrics',
    doctorName: 'Dr. Zainab Ibrahim',
    date: new Date().toISOString().split('T')[0],
    time: 'Evening',
    priority: 'Normal',
    status: 'Completed',
    notes: 'Follow-up after treatment',
  },
  {
    id: 'GH-AP-0006',
    patientId: 'GH-PT-00007',
    patientName: 'Hauwa Abdullahi',
    appointmentType: 'Consultation',
    department: 'Family Medicine',
    doctorName: 'Dr. Maryam Yusuf',
    date: new Date().toISOString().split('T')[0],
    time: 'Evening',
    priority: 'Normal',
    status: 'Cancelled',
    notes: 'Patient requested cancellation',
  },
  {
    id: 'GH-AP-0007',
    patientId: 'GH-PT-00010',
    patientName: 'Umar Hassan',
    appointmentType: 'Emergency',
    department: 'General Medicine',
    doctorName: 'Dr. Musa Abdullahi',
    date: new Date().toISOString().split('T')[0],
    time: 'Morning',
    priority: 'Critical',
    status: 'Completed',
    notes: 'Emergency chest pain evaluation',
  },
  {
    id: 'GH-AP-0008',
    patientId: 'GH-PT-00015',
    patientName: 'Salamatu Yakubu',
    appointmentType: 'Consultation',
    department: 'Pediatrics',
    doctorName: 'Dr. Zainab Ibrahim',
    date: new Date().toISOString().split('T')[0],
    time: '13:00',
    priority: 'Normal',
    status: 'Scheduled',
    notes: 'Pediatric wellness check',
  },
  // VIP Patient Appointments - Alhaji Usman Gwandu
  {
    id: 'APT-009',
    patientId: 'GH-PT-00016',
    patientName: 'Alhaji Usman Gwandu',
    appointmentType: 'Follow-up',
    department: 'General Medicine',
    doctorName: 'Dr. Musa Abdullahi',
    date: '2025-02-15',
    time: '10:00',
    priority: 'High',
    status: 'Scheduled',
    notes: 'Monthly diabetes and hypertension checkup - Nephrology consultation',
  },
  {
    id: 'APT-010',
    patientId: 'GH-PT-00016',
    patientName: 'Alhaji Usman Gwandu',
    appointmentType: 'Follow-up',
    department: 'General Medicine',
    doctorName: 'Dr. Musa Abdullahi',
    date: '2025-01-28',
    time: '10:00',
    priority: 'High',
    status: 'Completed',
    notes: 'Monthly routine checkup - Vitals monitoring',
  },
  {
    id: 'APT-011',
    patientId: 'GH-PT-00016',
    patientName: 'Alhaji Usman Gwandu',
    appointmentType: 'Follow-up',
    department: 'Nephrology',
    doctorName: 'Dr. Hauwa Sani',
    date: '2024-12-20',
    time: '11:00',
    priority: 'High',
    status: 'Completed',
    notes: 'CKD Stage 3 monitoring - Renal function assessment',
  },
  {
    id: 'APT-012',
    patientId: 'GH-PT-00016',
    patientName: 'Alhaji Usman Gwandu',
    appointmentType: 'Follow-up',
    department: 'Cardiology',
    doctorName: 'Dr. Yakubu Bello',
    date: '2024-08-15',
    time: '09:00',
    priority: 'High',
    status: 'Completed',
    notes: 'Post-cardiac event follow-up - ECG and Echo review',
  },
];

// Seed Invoices
export const seedInvoices: Invoice[] = [
  {
    id: 'INV-001',
    receiptId: 'GH-RC-0001',
    patientId: 'GH-PT-00001',
    patientName: 'Aisha Bello',
    invoiceType: 'Consultation',
    amount: 5000,
    paymentStatus: 'Paid',
    dateCreated: '2025-01-25T09:30:00',
  },
  {
    id: 'INV-002',
    receiptId: 'GH-RC-0002',
    patientId: 'GH-PT-00002',
    patientName: 'Ibrahim Yusuf',
    invoiceType: 'Admission',
    amount: 45000,
    paymentStatus: 'Partial',
    dateCreated: '2025-01-20T11:00:00',
  },
  {
    id: 'INV-003',
    receiptId: 'GH-RC-0003',
    patientId: 'GH-PT-00003',
    patientName: 'Fatima Usman',
    invoiceType: 'Lab',
    amount: 8000,
    paymentStatus: 'Paid',
    dateCreated: '2025-01-23T14:45:00',
  },
  {
    id: 'INV-004',
    receiptId: 'GH-RC-0004',
    patientId: 'GH-PT-00004',
    patientName: 'Musa Garba',
    invoiceType: 'Lab',
    amount: 12000,
    paymentStatus: 'Unpaid',
    dateCreated: '2025-01-25T17:00:00',
  },
  {
    id: 'INV-005',
    receiptId: 'GH-RC-0005',
    patientId: 'GH-PT-00007',
    patientName: 'Hauwa Abdullahi',
    invoiceType: 'Lab',
    amount: 6500,
    paymentStatus: 'Unpaid',
    dateCreated: '2025-01-24T15:30:00',
  },
  {
    id: 'INV-006',
    receiptId: 'GH-RC-0006',
    patientId: 'GH-PT-00009',
    patientName: 'Khadija Lawal',
    invoiceType: 'Pharmacy',
    amount: 3500,
    paymentStatus: 'Paid',
    dateCreated: '2025-01-19T11:15:00',
  },
  {
    id: 'INV-007',
    receiptId: 'GH-RC-0007',
    patientId: 'GH-PT-00010',
    patientName: 'Umar Hassan',
    invoiceType: 'Consultation',
    amount: 7000,
    paymentStatus: 'Paid',
    dateCreated: '2025-01-26T08:00:00',
  },
  {
    id: 'INV-008',
    receiptId: 'GH-RC-0008',
    patientId: 'GH-PT-00013',
    patientName: 'Amina Balarabe',
    invoiceType: 'Admission',
    amount: 60000,
    paymentStatus: 'Unpaid',
    dateCreated: '2025-01-24T17:00:00',
  },
  // VIP Patient Invoices - Alhaji Usman Gwandu
  {
    id: 'INV-009',
    receiptId: 'GH-RC-0009',
    patientId: 'GH-PT-00016',
    patientName: 'Alhaji Usman Gwandu',
    invoiceType: 'Consultation',
    amount: 15000,
    paymentStatus: 'Paid',
    dateCreated: '2025-01-28T11:00:00',
  },
  {
    id: 'INV-010',
    receiptId: 'GH-RC-0010',
    patientId: 'GH-PT-00016',
    patientName: 'Alhaji Usman Gwandu',
    invoiceType: 'Lab',
    amount: 45000,
    paymentStatus: 'Paid',
    dateCreated: '2025-01-28T11:30:00',
  },
  {
    id: 'INV-011',
    receiptId: 'GH-RC-0011',
    patientId: 'GH-PT-00016',
    patientName: 'Alhaji Usman Gwandu',
    invoiceType: 'Pharmacy',
    amount: 85000,
    paymentStatus: 'Paid',
    dateCreated: '2025-01-28T12:00:00',
  },
  {
    id: 'INV-012',
    receiptId: 'GH-RC-0012',
    patientId: 'GH-PT-00016',
    patientName: 'Alhaji Usman Gwandu',
    invoiceType: 'Consultation',
    amount: 15000,
    paymentStatus: 'Paid',
    dateCreated: '2024-12-20T10:00:00',
  },
  {
    id: 'INV-013',
    receiptId: 'GH-RC-0013',
    patientId: 'GH-PT-00016',
    patientName: 'Alhaji Usman Gwandu',
    invoiceType: 'Lab',
    amount: 38000,
    paymentStatus: 'Paid',
    dateCreated: '2024-12-20T10:30:00',
  },
  {
    id: 'INV-014',
    receiptId: 'GH-RC-0014',
    patientId: 'GH-PT-00016',
    patientName: 'Alhaji Usman Gwandu',
    invoiceType: 'Admission',
    amount: 450000,
    paymentStatus: 'Paid',
    dateCreated: '2023-04-05T15:00:00',
  },
  {
    id: 'INV-015',
    receiptId: 'GH-RC-0015',
    patientId: 'GH-PT-00016',
    patientName: 'Alhaji Usman Gwandu',
    invoiceType: 'Admission',
    amount: 1250000,
    paymentStatus: 'Paid',
    dateCreated: '2021-09-08T16:00:00',
  },
];

// Seed Staff
export const seedStaff: Staff[] = [
  {
    id: 'GH-ST-001',
    firstName: 'Sani',
    lastName: 'Lawal',
    fullName: 'Dr. Sani Lawal',
    gender: 'Male',
    email: 'sani.lawal@godiyahospital.ng',
    phoneNumber: '08012345671',
    address: 'No. 45 Hospital Road, Birnin Kebbi',
    department: 'Medical',
    role: 'Doctor',
    employmentType: 'Full-time',
    dateJoined: '2020-03-15',
    status: 'Active',
  },
  {
    id: 'GH-ST-002',
    firstName: 'Aisha',
    lastName: 'Bello',
    fullName: 'Aisha Bello',
    gender: 'Female',
    email: 'aisha.bello@godiyahospital.ng',
    phoneNumber: '08012345672',
    address: 'No. 12 Kano Road, Birnin Kebbi',
    department: 'Nursing',
    role: 'Nurse',
    employmentType: 'Full-time',
    dateJoined: '2019-06-20',
    status: 'Active',
  },
  {
    id: 'GH-ST-003',
    firstName: 'Fatima',
    lastName: 'Dauda',
    fullName: 'Fatima Dauda',
    gender: 'Female',
    email: 'fatima.dauda@godiyahospital.ng',
    phoneNumber: '08012345673',
    address: 'No. 78 Market Street, Birnin Kebbi',
    department: 'Pharmacy',
    role: 'Pharmacist',
    employmentType: 'Full-time',
    dateJoined: '2021-01-10',
    status: 'Active',
  },
  {
    id: 'GH-ST-004',
    firstName: 'Musa',
    lastName: 'Abdullahi',
    fullName: 'Musa Abdullahi',
    gender: 'Male',
    email: 'musa.abdullahi@godiyahospital.ng',
    phoneNumber: '08012345674',
    address: 'No. 34 Central Road, Birnin Kebbi',
    department: 'Laboratory',
    role: 'Lab Technician',
    employmentType: 'Full-time',
    dateJoined: '2020-08-15',
    status: 'Active',
  },
  {
    id: 'GH-ST-005',
    firstName: 'Zainab',
    lastName: 'Garba',
    fullName: 'Zainab Garba',
    gender: 'Female',
    email: 'zainab.garba@godiyahospital.ng',
    phoneNumber: '08012345675',
    address: 'No. 56 River Bank, Birnin Kebbi',
    department: 'Administration',
    role: 'Receptionist',
    employmentType: 'Full-time',
    dateJoined: '2021-03-01',
    status: 'Active',
  },
  {
    id: 'GH-ST-006',
    firstName: 'Ibrahim',
    lastName: 'Yusuf',
    fullName: 'Dr. Ibrahim Yusuf',
    gender: 'Male',
    email: 'ibrahim.yusuf@godiyahospital.ng',
    phoneNumber: '08012345676',
    address: 'No. 23 Township Road, Birnin Kebbi',
    department: 'Medical',
    role: 'Doctor',
    employmentType: 'Full-time',
    dateJoined: '2018-09-10',
    status: 'Active',
  },
  {
    id: 'GH-ST-007',
    firstName: 'Hauwa',
    lastName: 'Bello',
    fullName: 'Hauwa Bello',
    gender: 'Female',
    email: 'hauwa.bello@godiyahospital.ng',
    phoneNumber: '08012345677',
    address: 'No. 89 Sokoto Road, Birnin Kebbi',
    department: 'Nursing',
    role: 'Nurse',
    employmentType: 'Full-time',
    dateJoined: '2020-02-14',
    status: 'Active',
  },
  {
    id: 'GH-ST-008',
    firstName: 'Aliyu',
    lastName: 'Sani',
    fullName: 'Aliyu Sani',
    gender: 'Male',
    email: 'aliyu.sani@godiyahospital.ng',
    phoneNumber: '08012345678',
    address: 'No. 67 Argungu Road, Birnin Kebbi',
    department: 'Finance',
    role: 'Accountant',
    employmentType: 'Full-time',
    dateJoined: '2019-11-20',
    status: 'Active',
  },
  {
    id: 'GH-ST-009',
    firstName: 'Khadija',
    lastName: 'Musa',
    fullName: 'Khadija Musa',
    gender: 'Female',
    email: 'khadija.musa@godiyahospital.ng',
    phoneNumber: '08012345679',
    address: 'No. 45 Zuru Road, Birnin Kebbi',
    department: 'Nursing',
    role: 'Nurse',
    employmentType: 'Full-time',
    dateJoined: '2021-05-18',
    status: 'On Leave',
  },
  {
    id: 'GH-ST-010',
    firstName: 'Yusuf',
    lastName: 'Ibrahim',
    fullName: 'Dr. Yusuf Ibrahim',
    gender: 'Male',
    email: 'yusuf.ibrahim@godiyahospital.ng',
    phoneNumber: '08012345680',
    address: 'No. 12 Gwandu Road, Birnin Kebbi',
    department: 'Medical',
    role: 'Doctor',
    employmentType: 'Part-time',
    dateJoined: '2022-01-05',
    status: 'Active',
  },
  {
    id: 'GH-ST-011',
    firstName: 'Hafsat',
    lastName: 'Lawal',
    fullName: 'Hafsat Lawal',
    gender: 'Female',
    email: 'hafsat.lawal@godiyahospital.ng',
    phoneNumber: '08012345681',
    address: 'No. 90 Trade Fair, Birnin Kebbi',
    department: 'Pharmacy',
    role: 'Pharmacist',
    employmentType: 'Full-time',
    dateJoined: '2020-07-12',
    status: 'Active',
  },
  {
    id: 'GH-ST-012',
    firstName: 'Usman',
    lastName: 'Ahmed',
    fullName: 'Usman Ahmed',
    gender: 'Male',
    email: 'usman.ahmed@godiyahospital.ng',
    phoneNumber: '08012345682',
    address: 'No. 34 Police Barracks, Birnin Kebbi',
    department: 'Laboratory',
    role: 'Lab Technician',
    employmentType: 'Full-time',
    dateJoined: '2021-09-22',
    status: 'Active',
  },
  {
    id: 'GH-ST-013',
    firstName: 'Ramatu',
    lastName: 'Hassan',
    fullName: 'Ramatu Hassan',
    gender: 'Female',
    email: 'ramatu.hassan@godiyahospital.ng',
    phoneNumber: '08012345683',
    address: 'No. 56 State Secretariat, Birnin Kebbi',
    department: 'Nursing',
    role: 'Nurse',
    employmentType: 'Full-time',
    dateJoined: '2019-04-30',
    status: 'Active',
  },
  {
    id: 'GH-ST-014',
    firstName: 'Abdullahi',
    lastName: 'Umar',
    fullName: 'Dr. Abdullahi Umar',
    gender: 'Male',
    email: 'abdullahi.umar@godiyahospital.ng',
    phoneNumber: '08012345684',
    address: 'No. 78 New Layout, Birnin Kebbi',
    department: 'Medical',
    role: 'Doctor',
    employmentType: 'Full-time',
    dateJoined: '2017-12-01',
    status: 'Active',
  },
  {
    id: 'GH-ST-015',
    firstName: 'Halima',
    lastName: 'Aliyu',
    fullName: 'Halima Aliyu',
    gender: 'Female',
    email: 'halima.aliyu@godiyahospital.ng',
    phoneNumber: '08012345685',
    address: 'No. 23 College Road, Birnin Kebbi',
    department: 'Administration',
    role: 'Admin Officer',
    employmentType: 'Full-time',
    dateJoined: '2020-10-14',
    status: 'Active',
  },
  {
    id: 'GH-ST-016',
    firstName: 'Bashir',
    lastName: 'Suleiman',
    fullName: 'Bashir Suleiman',
    gender: 'Male',
    email: 'bashir.suleiman@godiyahospital.ng',
    phoneNumber: '08012345686',
    address: 'No. 45 Industrial Area, Birnin Kebbi',
    department: 'IT',
    role: 'IT Support',
    employmentType: 'Full-time',
    dateJoined: '2021-02-28',
    status: 'Active',
  },
  {
    id: 'GH-ST-017',
    firstName: 'Jamila',
    lastName: 'Mohammed',
    fullName: 'Jamila Mohammed',
    gender: 'Female',
    email: 'jamila.mohammed@godiyahospital.ng',
    phoneNumber: '08012345687',
    address: 'No. 67 Airport Road, Birnin Kebbi',
    department: 'Nursing',
    role: 'Nurse',
    employmentType: 'Full-time',
    dateJoined: '2022-03-15',
    status: 'Active',
  },
  {
    id: 'GH-ST-018',
    firstName: 'Suleiman',
    lastName: 'Bala',
    fullName: 'Suleiman Bala',
    gender: 'Male',
    email: 'suleiman.bala@godiyahospital.ng',
    phoneNumber: '08012345688',
    address: 'No. 89 Government House Road, Birnin Kebbi',
    department: 'Security',
    role: 'Security Guard',
    employmentType: 'Contract',
    dateJoined: '2020-01-10',
    status: 'Active',
  },
  {
    id: 'GH-ST-019',
    firstName: 'Safiya',
    lastName: 'Garba',
    fullName: 'Safiya Garba',
    gender: 'Female',
    email: 'safiya.garba@godiyahospital.ng',
    phoneNumber: '08012345689',
    address: 'No. 12 Stadium Road, Birnin Kebbi',
    department: 'Human Resources',
    role: 'HR Manager',
    employmentType: 'Full-time',
    dateJoined: '2018-05-20',
    status: 'Active',
  },
  {
    id: 'GH-ST-020',
    firstName: 'Ahmad',
    lastName: 'Yusuf',
    fullName: 'Ahmad Yusuf',
    gender: 'Male',
    email: 'ahmad.yusuf@godiyahospital.ng',
    phoneNumber: '08012345690',
    address: 'No. 34 University Road, Birnin Kebbi',
    department: 'Maintenance',
    role: 'Cleaner',
    employmentType: 'Part-time',
    dateJoined: '2021-07-01',
    status: 'Suspended', // Changed to test Reactivate button
  },
  {
    id: 'GH-ST-021',
    firstName: 'Salamatu',
    lastName: 'Usman',
    fullName: 'Salamatu Usman',
    gender: 'Female',
    email: 'salamatu.usman@godiyahospital.ng',
    phoneNumber: '08012345691',
    address: 'No. 56 Teachers Village, Birnin Kebbi',
    department: 'Nursing',
    role: 'Nurse',
    employmentType: 'Full-time',
    dateJoined: '2019-08-10',
    status: 'Active',
  },
  {
    id: 'GH-ST-022',
    firstName: 'Nasiru',
    lastName: 'Abubakar',
    fullName: 'Nasiru Abubakar',
    gender: 'Male',
    email: 'nasiru.abubakar@godiyahospital.ng',
    phoneNumber: '08012345692',
    address: 'No. 78 Old Market, Birnin Kebbi',
    department: 'Laboratory',
    role: 'Lab Technician',
    employmentType: 'Full-time',
    dateJoined: '2020-11-25',
    status: 'Active',
  },
  {
    id: 'GH-ST-023',
    firstName: 'Maryam',
    lastName: 'Bello',
    fullName: 'Dr. Maryam Bello',
    gender: 'Female',
    email: 'maryam.bello@godiyahospital.ng',
    phoneNumber: '08012345693',
    address: 'No. 45 Specialist Hospital, Birnin Kebbi',
    department: 'Medical',
    role: 'Doctor',
    employmentType: 'Full-time',
    dateJoined: '2019-02-14',
    status: 'Active',
  },
  {
    id: 'GH-ST-024',
    firstName: 'Sani',
    lastName: 'Mohammed',
    fullName: 'Sani Mohammed',
    gender: 'Male',
    email: 'sani.mohammed@godiyahospital.ng',
    phoneNumber: '08012345694',
    address: 'No. 67 Federal Low Cost, Birnin Kebbi',
    department: 'Pharmacy',
    role: 'Pharmacist',
    employmentType: 'Full-time',
    dateJoined: '2021-06-08',
    status: 'Active',
  },
  {
    id: 'GH-ST-025',
    firstName: 'Rukayya',
    lastName: 'Aliyu',
    fullName: 'Rukayya Aliyu',
    gender: 'Female',
    email: 'rukayya.aliyu@godiyahospital.ng',
    phoneNumber: '08012345695',
    address: 'No. 89 Housing Estate, Birnin Kebbi',
    department: 'Nursing',
    role: 'Nurse',
    employmentType: 'Full-time',
    dateJoined: '2020-04-20',
    status: 'Active',
  },
  {
    id: 'GH-ST-026',
    firstName: 'Aminu',
    lastName: 'Isah',
    fullName: 'Aminu Isah',
    gender: 'Male',
    email: 'aminu.isah@godiyahospital.ng',
    phoneNumber: '08012345696',
    address: 'No. 12 Emir\'s Palace Road, Birnin Kebbi',
    department: 'Finance',
    role: 'Accountant',
    employmentType: 'Full-time',
    dateJoined: '2018-10-15',
    status: 'Active',
  },
  {
    id: 'GH-ST-027',
    firstName: 'Hassana',
    lastName: 'Yakubu',
    fullName: 'Hassana Yakubu',
    gender: 'Female',
    email: 'hassana.yakubu@godiyahospital.ng',
    phoneNumber: '08012345697',
    address: 'No. 34 Bridge Head, Birnin Kebbi',
    department: 'Administration',
    role: 'Receptionist',
    employmentType: 'Full-time',
    dateJoined: '2022-02-01',
    status: 'Active',
  },
  {
    id: 'GH-ST-028',
    firstName: 'Kabiru',
    lastName: 'Sani',
    fullName: 'Dr. Kabiru Sani',
    gender: 'Male',
    email: 'kabiru.sani@godiyahospital.ng',
    phoneNumber: '08012345698',
    address: 'No. 56 Doctors Quarters, Birnin Kebbi',
    department: 'Medical',
    role: 'Doctor',
    employmentType: 'Full-time',
    dateJoined: '2017-07-20',
    status: 'Suspended',
  },
];

// Seed Bed Categories
export const seedBedCategories: BedCategory[] = [
  {
    id: 'GH-BED-001',
    categoryName: 'General Ward',
    pricePerDay: 5000,
    totalBeds: 20,
    occupiedBeds: 12,
    availableBeds: 8,
    description: 'Standard ward beds for general patient care',
    dateCreated: '2025-01-01T08:00:00',
    lastUpdated: '2025-02-04T10:30:00',
  },
  {
    id: 'GH-BED-002',
    categoryName: 'ICU Beds',
    pricePerDay: 25000,
    totalBeds: 8,
    occupiedBeds: 6,
    availableBeds: 2,
    description: 'Intensive Care Unit beds with advanced monitoring',
    dateCreated: '2025-01-01T08:00:00',
    lastUpdated: '2025-02-04T10:30:00',
  },
  {
    id: 'GH-BED-003',
    categoryName: 'Maternity Ward',
    pricePerDay: 8000,
    totalBeds: 15,
    occupiedBeds: 9,
    availableBeds: 6,
    description: 'Beds for maternity and post-delivery care',
    dateCreated: '2025-01-01T08:00:00',
    lastUpdated: '2025-02-04T10:30:00',
  },
  {
    id: 'GH-BED-004',
    categoryName: 'Pediatric Ward',
    pricePerDay: 6000,
    totalBeds: 12,
    occupiedBeds: 7,
    availableBeds: 5,
    description: 'Specialized beds for children and infants',
    dateCreated: '2025-01-01T08:00:00',
    lastUpdated: '2025-02-04T10:30:00',
  },
  {
    id: 'GH-BED-005',
    categoryName: 'Amenity Ward',
    pricePerDay: 15000,
    totalBeds: 10,
    occupiedBeds: 3,
    availableBeds: 7,
    description: 'Premium private rooms with enhanced amenities',
    dateCreated: '2025-01-01T08:00:00',
    lastUpdated: '2025-02-04T10:30:00',
  },
  {
    id: 'GH-BED-006',
    categoryName: 'Emergency Ward',
    pricePerDay: 10000,
    totalBeds: 6,
    occupiedBeds: 6,
    availableBeds: 0,
    description: 'Emergency department beds for critical cases',
    dateCreated: '2025-01-01T08:00:00',
    lastUpdated: '2025-02-04T10:30:00',
  },
];