// VIP Patient Data for Alhaji Usman Gwandu (GH-PT-00016)
// 15 years of medical history (2010-2025)

export const vipPatientId = 'GH-PT-00016';

// KPI Counts for VIP Patient
export const vipPatientKPIs = {
  prescriptions: 45,
  admissions: 7,
  labTestsCount: 78,
  findingsCount: 24,
  medications: 120,
  operations: 2,
  referrals: 3,
  surgeryRequests: 2,
};

// Vitals Data - Monthly monitoring over 15 years
export const vipVitalsData = [
  // Recent vitals (2024-2025) - Monthly monitoring
  { date: '2025-01-28', temperature: 36.5, bp: '148/92', pulse: 84, weight: 72, height: 168, rbs: 142 },
  { date: '2025-01-15', temperature: 36.6, bp: '145/90', pulse: 82, weight: 72, height: 168, rbs: 138 },
  { date: '2024-12-20', temperature: 36.7, bp: '150/94', pulse: 86, weight: 73, height: 168, rbs: 156 },
  { date: '2024-11-18', temperature: 36.4, bp: '146/88', pulse: 80, weight: 73, height: 168, rbs: 148 },
  { date: '2024-10-22', temperature: 36.6, bp: '152/96', pulse: 88, weight: 74, height: 168, rbs: 162 },
  { date: '2024-09-15', temperature: 36.5, bp: '144/86', pulse: 78, weight: 74, height: 168, rbs: 145 },
  { date: '2024-08-10', temperature: 36.7, bp: '148/90', pulse: 84, weight: 75, height: 168, rbs: 152 },
  { date: '2024-07-05', temperature: 36.6, bp: '146/88', pulse: 82, weight: 75, height: 168, rbs: 149 },
  { date: '2024-06-12', temperature: 36.5, bp: '150/92', pulse: 86, weight: 76, height: 168, rbs: 158 },
  { date: '2024-05-08', temperature: 36.8, bp: '145/90', pulse: 80, weight: 76, height: 168, rbs: 143 },
  // 2023 vitals
  { date: '2023-12-15', temperature: 36.6, bp: '142/88', pulse: 76, weight: 77, height: 168, rbs: 138 },
  { date: '2023-09-20', temperature: 36.7, bp: '148/92', pulse: 82, weight: 78, height: 168, rbs: 155 },
  { date: '2023-06-10', temperature: 36.5, bp: '150/94', pulse: 88, weight: 78, height: 168, rbs: 168 },
  { date: '2023-03-25', temperature: 37.2, bp: '156/98', pulse: 92, weight: 79, height: 168, rbs: 175 },
  // Earlier years - showing progression
  { date: '2022-11-12', temperature: 36.6, bp: '138/84', pulse: 74, weight: 80, height: 168, rbs: 132 },
  { date: '2022-05-18', temperature: 36.7, bp: '140/86', pulse: 76, weight: 81, height: 168, rbs: 128 },
  { date: '2021-08-22', temperature: 36.5, bp: '136/82', pulse: 72, weight: 82, height: 168, rbs: 145 },
  { date: '2020-10-15', temperature: 37.4, bp: '145/88', pulse: 88, weight: 83, height: 168, rbs: 165 },
  { date: '2019-06-08', temperature: 36.6, bp: '132/80', pulse: 70, weight: 84, height: 168, rbs: 118 },
  { date: '2018-09-14', temperature: 36.7, bp: '136/84', pulse: 74, weight: 85, height: 168, rbs: 142 },
];

// Consultations - Major medical visits over 15 years
export const vipConsultations = [
  {
    id: 1,
    date: '2025-01-28',
    doctor: 'Dr. Musa Abdullahi',
    department: 'General Medicine',
    diagnosis: 'Type 2 Diabetes Mellitus (Controlled), Essential Hypertension (Stage 2), Chronic Kidney Disease Stage 3',
    complaints: 'Routine monthly checkup, occasional dizziness, mild lower limb edema',
    observations: 'BP 148/92 mmHg, RBS 142 mg/dL. Patient compliant with medications. Mild peripheral edema noted. GFR 52 ml/min - stable. Advised to continue current medications and maintain low sodium diet. Next review in 4 weeks.',
  },
  {
    id: 2,
    date: '2024-12-20',
    doctor: 'Dr. Hauwa Sani',
    department: 'Nephrology',
    diagnosis: 'CKD Stage 3 - Stable',
    complaints: 'Follow-up nephrology consultation',
    observations: 'Creatinine 1.8 mg/dL (stable from previous). Proteinuria present. BP control improving. Continue ACE inhibitors and monitor renal function monthly.',
  },
  {
    id: 3,
    date: '2024-10-15',
    doctor: 'Dr. Musa Abdullahi',
    department: 'General Medicine',
    diagnosis: 'Poorly controlled Type 2 DM, HTN',
    complaints: 'Increased fatigue, polyuria, polydipsia',
    observations: 'RBS 162 mg/dL. HbA1c 8.2%. Insulin dose adjusted. Patient counseled on diet compliance and regular exercise.',
  },
  {
    id: 4,
    date: '2023-08-15',
    doctor: 'Dr. Yakubu Bello',
    department: 'Cardiology',
    diagnosis: 'Hypertensive Heart Disease, Controlled Diabetes',
    complaints: 'Post-cardiac event follow-up',
    observations: 'ECG shows LVH. Echo normal EF. Patient stable on current cardiac medications. Continue Aspirin, ACE inhibitors, and statins.',
  },
  {
    id: 5,
    date: '2023-03-28',
    doctor: 'Dr. Musa Abdullahi',
    department: 'General Medicine',
    diagnosis: 'Acute Kidney Injury on CKD Stage 3, Dehydration',
    complaints: 'Reduced urine output, confusion, weakness',
    observations: 'Creatinine elevated to 3.2 mg/dL (baseline 1.6). Admitted for IV hydration and close monitoring. Metformin withheld temporarily.',
  },
  {
    id: 6,
    date: '2021-08-25',
    doctor: 'Dr. Yakubu Bello',
    department: 'Cardiology',
    diagnosis: 'Acute Coronary Syndrome - NSTEMI',
    complaints: 'Severe chest pain, shortness of breath, diaphoresis',
    observations: 'Troponin elevated. ECG changes consistent with NSTEMI. Admitted to ICU. Cardiac catheterization showed 70% LAD stenosis. Medical management initiated.',
  },
  {
    id: 7,
    date: '2020-01-15',
    doctor: 'Dr. Zainab Ibrahim',
    department: 'Respiratory Medicine',
    diagnosis: 'Community Acquired Pneumonia',
    complaints: 'High fever, productive cough, difficulty breathing',
    observations: 'CXR shows right lower lobe consolidation. SpO2 88% on room air. Admitted for IV antibiotics and oxygen therapy. Diabetes poorly controlled during illness.',
  },
  {
    id: 8,
    date: '2018-11-20',
    doctor: 'Dr. Hauwa Sani',
    department: 'Nephrology',
    diagnosis: 'Newly diagnosed CKD Stage 3',
    complaints: 'Fatigue, mild edema, routine DM follow-up',
    observations: 'Creatinine 1.6 mg/dL, GFR 48 ml/min. Proteinuria detected. Likely diabetic nephropathy. Started on ACE inhibitor for renal protection.',
  },
];

// Medical History - Complete 15-year medical timeline
export const vipMedicalHistory = [
  { type: 'Chronic Disease', condition: 'Type 2 Diabetes Mellitus', diagnosedDate: '2010-03-20', status: 'Active' },
  { type: 'Chronic Disease', condition: 'Essential Hypertension', diagnosedDate: '2012-07-15', status: 'Active' },
  { type: 'Chronic Disease', condition: 'Chronic Kidney Disease Stage 3 (Diabetic Nephropathy)', diagnosedDate: '2018-11-20', status: 'Active' },
  { type: 'Chronic Disease', condition: 'Dyslipidemia', diagnosedDate: '2013-05-10', status: 'Active' },
  { type: 'Cardiac Event', condition: 'Non-ST Elevation Myocardial Infarction (NSTEMI)', date: '2021-08-25', hospital: 'Godiya Hospital', notes: '70% LAD stenosis, managed medically' },
  { type: 'Acute Illness', condition: 'Community Acquired Pneumonia', date: '2020-01-15', hospital: 'Godiya Hospital', notes: 'Required admission and oxygen therapy' },
  { type: 'Acute Illness', condition: 'Acute Kidney Injury on CKD', date: '2023-03-28', hospital: 'Godiya Hospital', notes: 'Required IV hydration, creatinine normalized' },
  { type: 'Allergy', condition: 'Penicillin', severity: 'Severe', notes: 'Developed severe rash and angioedema in 2008. Avoid all penicillin-based antibiotics and cephalosporins' },
  { type: 'Family History', condition: 'Father - Chronic Kidney Failure (deceased)', notes: 'Died at age 68' },
  { type: 'Family History', condition: 'Mother - Type 2 Diabetes Mellitus (deceased)', notes: 'Died at age 72' },
  { type: 'Social History', condition: 'Non-smoker, Occasional kola nut', notes: 'Retired civil servant. Lives with son (Dr. Aminu). Uses wheelchair for mobility.' },
];

// Admissions - 7 admissions over 15 years
export const vipAdmissionsData = [
  {
    id: 1,
    ward: 'Private Ward',
    bed: 'PW-1',
    dateAdmitted: '2023-03-28',
    dateDischarged: '2023-04-05',
    reason: 'Acute Kidney Injury on CKD Stage 3, Dehydration',
    status: 'Discharged',
    notes: 'Creatinine 3.2 mg/dL on admission, normalized to 1.7 mg/dL with IV hydration. Metformin withheld and reintroduced gradually.',
  },
  {
    id: 2,
    ward: 'ICU',
    bed: 'ICU-1',
    dateAdmitted: '2021-08-25',
    dateDischarged: '2021-09-08',
    reason: 'Acute Coronary Syndrome - NSTEMI, Coronary Artery Disease',
    status: 'Discharged',
    notes: '14 days in ICU. Cardiac catheterization showed 70% LAD stenosis. Managed medically with dual antiplatelet therapy, statins, and ACE inhibitors. Patient declined PCI.',
  },
  {
    id: 3,
    ward: 'General Ward B',
    bed: 'B-8',
    dateAdmitted: '2020-01-15',
    dateDischarged: '2020-01-28',
    reason: 'Community Acquired Pneumonia, Type 2 Respiratory Failure',
    status: 'Discharged',
    notes: 'Right lower lobe pneumonia. Required oxygen therapy (4L/min). IV Ceftriaxone and Azithromycin for 10 days. Blood glucose poorly controlled during admission.',
  },
  {
    id: 4,
    ward: 'Private Ward',
    bed: 'PW-2',
    dateAdmitted: '2018-11-25',
    dateDischarged: '2018-12-02',
    reason: 'Newly diagnosed CKD Stage 3 - Investigations and Management',
    status: 'Discharged',
    notes: 'Comprehensive renal workup. Renal ultrasound showed bilateral small kidneys. Started on renal protection therapy.',
  },
  {
    id: 5,
    ward: 'General Ward A',
    bed: 'A-15',
    dateAdmitted: '2016-05-10',
    dateDischarged: '2016-05-18',
    reason: 'Hypoglycemic Episode, Falls',
    status: 'Discharged',
    notes: 'Found unconscious at home with RBS 42 mg/dL. Recovered with IV dextrose. Insulin regimen adjusted.',
  },
  {
    id: 6,
    ward: 'Private Ward',
    bed: 'PW-1',
    dateAdmitted: '2014-09-22',
    dateDischarged: '2014-09-30',
    reason: 'Uncontrolled Type 2 Diabetes, Hyperglycemia',
    status: 'Discharged',
    notes: 'RBS 385 mg/dL. Started on insulin therapy. Diabetes education provided.',
  },
  {
    id: 7,
    ward: 'General Ward B',
    bed: 'B-4',
    dateAdmitted: '2012-12-05',
    dateDischarged: '2012-12-10',
    reason: 'Hypertensive Emergency',
    status: 'Discharged',
    notes: 'BP 210/120 mmHg with headache and blurred vision. Managed with IV antihypertensives. BP control achieved.',
  },
];

// Prescriptions - Current and historical medications
export const vipPrescriptionsData = [
  // Current medications (January 2025)
  {
    id: 1,
    drug: 'Metformin 1000mg',
    dosage: '1 tablet twice daily (with meals)',
    duration: '30 days',
    doctor: 'Dr. Musa Abdullahi',
    date: '2025-01-28',
    status: 'Fulfilled',
  },
  {
    id: 2,
    drug: 'Insulin Glargine (Lantus) 100 units/mL',
    dosage: '20 units subcutaneous at bedtime',
    duration: '30 days',
    doctor: 'Dr. Musa Abdullahi',
    date: '2025-01-28',
    status: 'Fulfilled',
  },
  {
    id: 3,
    drug: 'Amlodipine 10mg',
    dosage: '1 tablet once daily (morning)',
    duration: '30 days',
    doctor: 'Dr. Musa Abdullahi',
    date: '2025-01-28',
    status: 'Fulfilled',
  },
  {
    id: 4,
    drug: 'Aspirin 75mg (enteric coated)',
    dosage: '1 tablet once daily (morning)',
    duration: '30 days',
    doctor: 'Dr. Musa Abdullahi',
    date: '2025-01-28',
    status: 'Fulfilled',
  },
  {
    id: 5,
    drug: 'Atorvastatin 40mg',
    dosage: '1 tablet once daily (at night)',
    duration: '30 days',
    doctor: 'Dr. Musa Abdullahi',
    date: '2025-01-28',
    status: 'Fulfilled',
  },
  {
    id: 6,
    drug: 'Lisinopril 20mg',
    dosage: '1 tablet once daily (morning)',
    duration: '30 days',
    doctor: 'Dr. Musa Abdullahi',
    date: '2025-01-28',
    status: 'Fulfilled',
  },
  {
    id: 7,
    drug: 'Furosemide 40mg',
    dosage: '1 tablet once daily (morning)',
    duration: '30 days',
    doctor: 'Dr. Musa Abdullahi',
    date: '2025-01-28',
    status: 'Fulfilled',
  },
  // Previous prescriptions (December 2024)
  {
    id: 8,
    drug: 'Metformin 1000mg',
    dosage: '1 tablet twice daily',
    duration: '30 days',
    doctor: 'Dr. Musa Abdullahi',
    date: '2024-12-20',
    status: 'Fulfilled',
  },
  {
    id: 9,
    drug: 'Insulin Glargine 100 units/mL',
    dosage: '18 units at bedtime',
    duration: '30 days',
    doctor: 'Dr. Musa Abdullahi',
    date: '2024-12-20',
    status: 'Fulfilled',
  },
  {
    id: 10,
    drug: 'Amlodipine 10mg',
    dosage: '1 tablet daily',
    duration: '30 days',
    doctor: 'Dr. Hauwa Sani',
    date: '2024-12-20',
    status: 'Fulfilled',
  },
  // Additional medications from consultations
  {
    id: 11,
    drug: 'Clopidogrel 75mg',
    dosage: '1 tablet daily (post-cardiac event)',
    duration: '90 days',
    doctor: 'Dr. Yakubu Bello',
    date: '2023-08-15',
    status: 'Fulfilled',
  },
  {
    id: 12,
    drug: 'Ceftriaxone 1g IV',
    dosage: 'Once daily',
    duration: '10 days',
    doctor: 'Dr. Zainab Ibrahim',
    date: '2020-01-15',
    status: 'Fulfilled',
  },
];

// Nurse Notes - Key nursing observations
export const vipNurseNotes = [
  {
    id: 1,
    date: '2025-01-28 09:00',
    nurse: 'Nurse Aisha Bello',
    shift: 'Day Shift',
    notes: 'VIP patient arrived for routine monthly checkup. Vitals taken: BP 148/92, Pulse 84, Temp 36.5°C, RBS 142 mg/dL. Patient in wheelchair, assisted by son. Medications administered: Morning doses of Metformin 1000mg, Amlodipine 10mg, Lisinopril 20mg, Aspirin 75mg, Furosemide 40mg.',
    observations: 'Patient alert and oriented. Mild peripheral edema noted in lower limbs. No complaints of chest pain or shortness of breath. Diet compliance good per patient report.',
  },
  {
    id: 2,
    date: '2023-04-02 14:30',
    nurse: 'Nurse Hauwa Bello',
    shift: 'Day Shift',
    notes: 'Day 5 of admission for AKI. Creatinine trending down (2.1 mg/dL from 3.2). IV fluids maintained at 80 mL/hr. Urine output adequate (1200 mL/24hr). Patient tolerating oral diet.',
    observations: 'Patient improving. Less confused than previous days. Family members present and supportive.',
  },
  {
    id: 3,
    date: '2021-09-01 22:00',
    nurse: 'Nurse Zainab Garba',
    shift: 'Night Shift',
    notes: 'ICU Day 7 post-NSTEMI. Patient stable. Cardiac monitor shows normal sinus rhythm. No chest pain. Telemetry monitoring continuous.',
    observations: 'Patient resting comfortably. Vital signs stable throughout shift. No arrhythmias detected.',
  },
  {
    id: 4,
    date: '2020-01-20 10:00',
    nurse: 'Nurse Aisha Bello',
    shift: 'Day Shift',
    notes: 'Day 5 pneumonia treatment. Oxygen saturation improved to 94% on 2L/min (down from 4L/min). Completing IV antibiotics course. Less productive cough.',
    observations: 'Patient showing significant improvement. Afebrile for 48 hours. Ambulating with assistance.',
  },
];

// Lab Tests - Comprehensive testing over 15 years
export const vipLabTests = [
  // Recent tests (2025)
  {
    id: 1,
    testName: 'Fasting Blood Sugar',
    requestedBy: 'Dr. Musa Abdullahi',
    date: '2025-01-28',
    status: 'Completed',
    result: '138 mg/dL (Elevated)',
  },
  {
    id: 2,
    testName: 'HbA1c',
    requestedBy: 'Dr. Musa Abdullahi',
    date: '2025-01-28',
    status: 'Completed',
    result: '7.8% (Target <7%)',
  },
  {
    id: 3,
    testName: 'Serum Creatinine',
    requestedBy: 'Dr. Musa Abdullahi',
    date: '2025-01-28',
    status: 'Completed',
    result: '1.8 mg/dL (Elevated) - Stable from baseline',
  },
  {
    id: 4,
    testName: 'eGFR',
    requestedBy: 'Dr. Musa Abdullahi',
    date: '2025-01-28',
    status: 'Completed',
    result: '52 mL/min/1.73m² (CKD Stage 3a)',
  },
  {
    id: 5,
    testName: 'Urine Protein/Creatinine Ratio',
    requestedBy: 'Dr. Hauwa Sani',
    date: '2024-12-20',
    status: 'Completed',
    result: '450 mg/g (Moderate proteinuria)',
  },
  {
    id: 6,
    testName: 'Complete Blood Count',
    requestedBy: 'Dr. Musa Abdullahi',
    date: '2025-01-28',
    status: 'Completed',
    result: 'Hb: 11.2 g/dL (Mild anemia), WBC: 7,200/μL, Platelets: 245,000/μL',
  },
  {
    id: 7,
    testName: 'Lipid Profile',
    requestedBy: 'Dr. Musa Abdullahi',
    date: '2025-01-28',
    status: 'Completed',
    result: 'Total Cholesterol: 198 mg/dL, LDL: 118 mg/dL, HDL: 42 mg/dL, Triglycerides: 188 mg/dL',
  },
  {
    id: 8,
    testName: 'Liver Function Tests',
    requestedBy: 'Dr. Musa Abdullahi',
    date: '2025-01-28',
    status: 'Completed',
    result: 'All parameters within normal limits',
  },
  {
    id: 9,
    testName: 'Serum Electrolytes',
    requestedBy: 'Dr. Musa Abdullahi',
    date: '2025-01-28',
    status: 'Completed',
    result: 'Na: 138 mEq/L, K: 4.2 mEq/L, Cl: 102 mEq/L - Normal',
  },
  {
    id: 10,
    testName: 'ECG (12-lead)',
    requestedBy: 'Dr. Yakubu Bello',
    date: '2024-08-15',
    status: 'Completed',
    result: 'Sinus rhythm, LVH pattern, no acute ischemic changes',
  },
  // Historical tests
  {
    id: 11,
    testName: 'Echocardiography',
    requestedBy: 'Dr. Yakubu Bello',
    date: '2023-08-20',
    status: 'Completed',
    result: 'EF 55%, Mild LV hypertrophy, No regional wall motion abnormalities',
  },
  {
    id: 12,
    testName: 'Cardiac Troponin I',
    requestedBy: 'Dr. Yakubu Bello',
    date: '2021-08-25',
    status: 'Completed',
    result: '2.8 ng/mL (Elevated - consistent with NSTEMI)',
  },
  {
    id: 13,
    testName: 'Chest X-Ray',
    requestedBy: 'Dr. Zainab Ibrahim',
    date: '2020-01-15',
    status: 'Completed',
    result: 'Right lower lobe consolidation - Community acquired pneumonia',
  },
  {
    id: 14,
    testName: 'Renal Ultrasound',
    requestedBy: 'Dr. Hauwa Sani',
    date: '2018-11-25',
    status: 'Completed',
    result: 'Bilateral small kidneys (R: 8.2cm, L: 8.5cm). Increased echogenicity. Consistent with chronic kidney disease.',
  },
];

// Medical Findings - Key diagnostic findings
export const vipFindings = [
  {
    id: 1,
    type: 'Laboratory',
    finding: 'HbA1c - Diabetes Control Assessment',
    result: '7.8% - Fair control, target <7%. Continue current insulin and oral hypoglycemic regimen with dose adjustment.',
    date: '2025-01-28',
    doctor: 'Dr. Musa Abdullahi',
  },
  {
    id: 2,
    type: 'Laboratory',
    finding: 'Renal Function Panel',
    result: 'Creatinine 1.8 mg/dL, eGFR 52 mL/min - CKD Stage 3a, stable. Continue renal protective therapy.',
    date: '2025-01-28',
    doctor: 'Dr. Musa Abdullahi',
  },
  {
    id: 3,
    type: 'Laboratory',
    finding: 'Proteinuria Assessment',
    result: 'Urine Protein/Creatinine ratio 450 mg/g - Moderate proteinuria, consistent with diabetic nephropathy.',
    date: '2024-12-20',
    doctor: 'Dr. Hauwa Sani',
  },
  {
    id: 4,
    type: 'Imaging',
    finding: 'Echocardiography',
    result: 'EF 55% (normal), Mild LV hypertrophy secondary to hypertension. No valvular abnormalities.',
    date: '2023-08-20',
    doctor: 'Dr. Yakubu Bello',
  },
  {
    id: 5,
    type: 'Laboratory',
    finding: 'Cardiac Biomarkers - Troponin I',
    result: '2.8 ng/mL - Markedly elevated, consistent with acute myocardial infarction (NSTEMI).',
    date: '2021-08-25',
    doctor: 'Dr. Yakubu Bello',
  },
  {
    id: 6,
    type: 'Procedure',
    finding: 'Cardiac Catheterization',
    result: 'Significant 70% stenosis in Left Anterior Descending (LAD) artery. Medical management recommended due to patient preference.',
    date: '2021-08-27',
    doctor: 'Dr. Yakubu Bello',
  },
  {
    id: 7,
    type: 'Imaging',
    finding: 'Chest X-Ray',
    result: 'Right lower lobe consolidation consistent with community acquired pneumonia.',
    date: '2020-01-15',
    doctor: 'Dr. Zainab Ibrahim',
  },
  {
    id: 8,
    type: 'Imaging',
    finding: 'Renal Ultrasound',
    result: 'Bilateral small kidneys (Right: 8.2cm, Left: 8.5cm) with increased echogenicity - Chronic kidney disease.',
    date: '2018-11-25',
    doctor: 'Dr. Hauwa Sani',
  },
];
